---
- include_vars: ../../common_vars.yml

- name: Starting Elasticsearch
  become: yes
  service:
    name: elasticsearch
    state: started
  register: ElasticsearchStarted

- name: Wait for Elasticsearch port 9200 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9200
    delay: 10

- name: curl put good-mapping.json
  shell: "curl -XPUT 'http://localhost:9200/good' -d @{{es_dir}}/good-mapping.json"

- name: curl put bad-mapping.json
  shell: "curl -XPUT 'http://localhost:9200/bad' -d @{{es_dir}}/bad-mapping.json"

- name: Starting nsqd
  become: yes
  service:
    name: nsqd_init
    state: started
  register: NsqdStarted

- name: Starting nsqlookupd
  become: yes
  service:
    name: nsqlookupd_init
    state: started
  register: NsqlookupdStarted

- name: Starting nsqadmin
  become: yes
  service:
    name: nsqadmin_init
    state: started
  register: NsqadminStarted

- name: Wait for the NSQ services to start
  wait_for:
    port: "{{item}}"
    delay: 1
  with_items:
    - 4151
    - 4161
    - 4171

- name: Starting Kibana
  become: yes
  service:
    name: kibana4_init
    state: started

- name: add "good" index pattern to Kibana
  shell: >
      curl -XPUT http://localhost:9200/.kibana/index-pattern/good -d '{"title" : "good",  "timeFieldName" : "collector_tstamp"}'

- name: add "bad" index pattern to Kibana
  shell: >
      curl -XPUT http://localhost:9200/.kibana/index-pattern/bad -d '{"title" : "bad",  "timeFieldName" : "failure_tstamp"}'

- name: make "good" index pattern default
  shell: >
      curl -XPUT http://localhost:9200/.kibana/config/4.0.1 -d '{"defaultIndex" : "good"}'

- name: Create new topic for RawEvents
  shell: "curl -X POST http://127.0.0.1:4151/topic/create?topic=RawEvents"

- name: Create new topic for BadEvents
  shell: "curl -X POST http://127.0.0.1:4151/topic/create?topic=BadEvents"

- name: Create new topic for EnrichedEvents
  shell: "curl -X POST http://127.0.0.1:4151/topic/create?topic=EnrichedEvents"

- name: Create new topic for BadEnrichedEvents
  shell: "curl -X POST http://127.0.0.1:4151/topic/create?topic=BadEnrichedEvents"
