---
sudo: required
language: go

go:
  - 1.8

services:
  - postgresql


before_install:
  - sudo apt-get update -qq

install:
  - sudo pip install setuptools
  - sudo pip install ansible

before_script:
  - ansible-playbook -i provisioning/inventory provisioning/with_building_ui_and_go_projects.yml --connection=local --sudo

script:
  - ./integration/integration_test.sh
