---
- include_vars: ../../common_vars.yml

- name: Set variables
  set_fact:
    control_plane_dir: '{{playbook_dir}}/resources/control-plane'

- name: Copy Control API to executables dir
  become: yes
  synchronize:
    src: "{{executables_dir}}/snowplow-mini-control-plane-api"
    dest: "{{executables_dir}}"

- name: Copy VERSION file to /home/ubuntu/snowplow for Control API
  become: yes
  synchronize:
     src: "{{playbook_dir}}/../VERSION"
     dest: "{{main_dir}}"

- name: Copy Caddy executable to executables dir
  become: yes
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  synchronize:
    src: "{{executables_dir}}/caddy"
    dest: "{{executables_dir}}"

- name: Set owner of the main directory
  become: yes
  shell: "chown -R ubuntu:ubuntu {{main_dir}} && chmod 755 -R {{main_dir}}"
