version_file_path = "/home/ubuntu/snowplow/VERSION"

# for getting IP address of the running EC2 instance
# for more information visit:
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
EC2_meta_service_url = "http://169.254.169.254/latest/meta-data/public-ipv4"

[directories]
enrichments = "/home/ubuntu/snowplow/configs/enrichments" #directory which all the enrichments file are in
config = "/home/ubuntu/snowplow/configs" #directory which all the configs are in

[config_file_names]
caddy = "Caddyfile"
iglu_resolver = "iglu-resolver.json"

[init_scripts]
stream_collector = "snowplow_stream_collector"
stream_enrich = "snowplow_stream_enrich"
es_loader_good = "snowplow_elasticsearch_loader_good"
es_loader_bad = "snowplow_elasticsearch_loader_bad"
iglu = "iglu_server_0.3.0"
caddy = "caddy_init"

[PSQL]
user = "snowplow"
password = "snowplow"
database = "iglu"
adddress = "127.0.0.1:5432"
